#+title: The Top Five Regrets of The Dying
#+roam_tags: books

A book by Bronnie Ware.

* Abstract

After too many years of unfulfilling work, Bronnie Ware began searching for a job with heart. Despite having no formal qualifications or experience, she found herself in palliative care. Over the years she spent tending to the needs of those who were dying, Bronnie's life was transformed. Later, she wrote an Internet blog about the most common regrets expressed to her by the people she had cared for.

* Summary (taken from this [[https://www.theguardian.com/lifeandstyle/2012/feb/01/top-five-regrets-of-the-dying][article]])

** I wish I'd had the courage to live a life true to myself, not the life others expected of me

This was the most common regret of all. When people realise that their life is almost over and look back clearly on it, it is easy to see how many dreams have gone unfulfilled. Most people had not honoured even a half of their dreams and had to die knowing that it was due to choices they had made, or not made. Health brings a freedom very few realise, until they no longer have it.

** I wish I hadn't worked so hard

This came from every male patient that I nursed. They missed their children's youth and their partner's companionship. Women also spoke of this regret, but as most were from an older generation, many of the female patients had not been breadwinners. All of the men I nursed deeply regretted spending so much of their lives on the treadmill of a work existence.

** I wish I'd had the courage to express my feelings

Many people suppressed their feelings in order to keep peace with others. As a result, they settled for a mediocre existence and never became who they were truly capable of becoming. Many developed illnesses relating to the bitterness and resentment they carried as a result.

** I wish I had stayed in touch with my friends

Often they would not truly realise the full benefits of old friends until their dying weeks and it was not always possible to track them down. Many had become so caught up in their own lives that they had let golden friendships slip by over the years. There were many deep regrets about not giving friendships the time and effort that they deserved. Everyone misses their friends when they are dying.

** I wish that I had let myself be happier

This is a surprisingly common one. Many did not realise until the end that happiness is a choice. They had stayed stuck in old patterns and habits. The so-called 'comfort' of familiarity overflowed into their emotions, as well as their physical lives. Fear of change had them pretending to others, and to their selves, that they were content, when deep within, they longed to laugh properly and have silliness in their life again.

* Critique

** TODO Look if what is in this book is credible

* How I was made aware of it

- [[https://www.youtube.com/watch?v=WQWiLZ1M6xw&feature=share][20 Life Lessons I Learned in 2020 (Ali Abdaal)]]

* Sourcing

- [[https://www.amazon.de/Top-Five-Regrets-Dying-Transformed/dp/145250234X][Buy on Amazon]]
